### ISSUE TITLE
multiple instances

### ISSUE THREAD

**Issue by clrblnd** [mrhenry/mr-slides#2]
Small hick-up currently when implementing 2 or more instances on 1 page

https://youtu.be/vegT_cNVCH8

**Comment by yvesvanbroekhoven** [comment]
You can give a navigation selector as option, when you give a unique selector, this issue will be solved.

```
<div
  ...
  data-mr-slides-nav="#unique-bullet-nav">
  ...
</div>

<div id="unique-bullet-nav" class="bullet-nav">
  ...
</div>
```

I've updated [README](https://github.com/mrhenry/mr-slides) with this example.
